const movies = [
    {
        title: 'title1',
        id: 1,
        genre: 'Adventure',
        producer: 'producer1',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '20/10/2021',
        availableQuantity: 15,
    },
    {
        title: 'title2',
        id: 2,
        genre: 'Animated',
        producer: 'producer2',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '04/10/2022',
        availableQuantity: 15,
    },    
    {
        title: 'title3',
        id: 3,
        genre: 'Comedy',
        producer: 'producer3',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '10/10/2022',
        availableQuantity: 15,
    },
    {
        title: 'title4',
        id: 4,
        genre: 'Drama',
        producer: 'producer4',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '10/11/2022',
        availableQuantity: 20,
    },
    {
        title: 'title5',
        id: 5,
        genre: 'Historical',
        producer: 'producer5',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '24/11/2022',
        availableQuantity: 20,
    },
    {
        title: 'title6',
        id: 6,
        genre: 'Horror',
        producer: 'producer6',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '10/10/2022',
        availableQuantity: 10,
    },    
    {
        title: 'title7',
        id: 7,
        genre: 'Musical',
        producer: 'producer7',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '11/12/2022',
        availableQuantity: 15,
    },    
    {
        title: 'title8',
        id: 8,
        genre: 'Romance',
        producer: 'producer8',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '12/12/2022',
        availableQuantity: 20,
    },
    {
        title: 'title9',
        id: 9,
        genre: 'Science Fiction',
        producer: 'producer9',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '24/12/2022',
        availableQuantity: 10,
    },
    {
        title: 'title10',
        id: 10,
        genre: 'Thriller',
        producer: 'producer10',
        actors: ['actor1', 'actor2', 'actor3'],
        releasedYear: '25/12/2022',
        availableQuantity: 10,
    },
    
        {
            id: 10,
            name: 'Thriller',
            description: 'A thriller film evokes excitement and suspense in the audience. A common theme in thrillers involves innocent people dealing with a deranged adversary.  Examples of thrillers: The Silence of the Lambs, The Sixth Sense, The Da Vinci Code, Shutter Island',
            availableMovies: 10
        },
        
    ]
    
   module.exports = movies;